name = "tblite"
version = "0.5.0"
license = "LGPL-3.0-or-later"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
description = "Light-weight tight-binding framework"
keywords = ["quantum-chemistry", "tight-binding", "xtb"]
copyright = "Copyright 2021 S. Ehlert"

[build]
external-modules = ["ifport"]
link = ["lapack", "blas"]
auto-tests = false

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib"
mctc-lib.tag = "v0.3.2"
multicharge.git = "https://github.com/grimme-lab/multicharge"
multicharge.tag = "v0.3.0"
dftd4.git = "https://github.com/dftd4/dftd4"
dftd4.tag = "v3.7.0"
s-dftd3.git = "https://github.com/dftd3/simple-dftd3"
s-dftd3.tag = "v1.2.1"
toml-f.git = "https://github.com/toml-f/toml-f"
toml-f.tag = "v0.4.2"

[dev-dependencies]
mstore.git = "https://github.com/grimme-lab/mstore"
mstore.tag = "v0.3.0"

[[test]]
name = "unit-tester"
source-dir = "test/unit"
